### PR TITLE
Add cooldown functionality to scaling policies and storage backend.

### LINKED ISSUE #49: Add cooldown functionality to job group scaling
**Describe the solution you'd like.**
Cooldown is a feature of autoscaling which can help ensure previous scaling activities have a chance to impact the load on an application before another scaling event is triggered. The recent addition of scaling event state tracking, now allows Sherpa to include cooldowns within its scaling decision tree. 

AWS - https://docs.aws.amazon.com/autoscaling/ec2/userguide/Cooldown.html
Google - https://cloud.google.com/compute/docs/autoscaler/
Microsoft - https://docs.microsoft.com/en-us/azure/azure-monitor/platform/autoscale-virtual-machine-scale-sets?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fvirtual-machine-scale-sets%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json

### PR DESCRIPTION
**Pull request by jrasell**
Sherpa policies now allow the specifying of a cooldown as a time
duration in seconds. When a scaling activity is requested, the
cooldown is checked against the last scaling event for the job
group. If the last event has occurred within the cooldown period,
the scaling request will be denied.

Closes #49

### CODE REVIEW

**Comment by commarla** [comment]
Hi @jrasell the corresponding meta is missing. Is it on purpose ?

**Comment by jrasell** [comment]
@commarla could you elaborate on what you mean?

**Comment by commarla** [comment]
@jrasell maybe I missed it but I didn't see the corresponding nomad meta for the cooldown feature in your pr.

**Comment by jrasell** [comment]
@commarla oh yeah, good shout. I have to fix up the conflicts when I get time so i'll address that also. Thanks a lot for your help!

**Pull request merged**
